version: '3.8'

services:
  web:
    build: .
    container_name: plant_disease_web
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app
